FROM amazon/aws-sam-cli-build-image-ruby2.7

# Ensure minimum required SAM version.
RUN pip install awscli && \
    pip uninstall --yes aws-sam-cli && \
    pip install aws-sam-cli==v1.15.0

WORKDIR /var/task
